services:
  cypress-firefox:
    image: cypress/included:12.17.4
    working_dir: /e2e
    volumes:
      - .:/e2e
    entrypoint: ["cypress", "run", "--browser", "firefox"]

  cypress-chrome:
    image: cypress/included:12.17.4
    working_dir: /e2e
    volumes:
      - .:/e2e
    entrypoint: ["cypress", "run", "--browser", "chrome"]
